export enum PeriodoEstado {
  BORRADOR = 'BORRADOR',
  POSTULACION_ABIERTA = 'POSTULACION_ABIERTA',
  POSTULACION_CERRADA = 'POSTULACION_CERRADA',
  EN_CURSO = 'EN_CURSO',
  ARCHIVADO = 'ARCHIVADO',
}
