export enum NotificacionCanal {
  EN_APP = 'EN_APP',
  EMAIL = 'EMAIL',
}

export enum NotificacionTipo {
  PAT_ENTREGADO = 'PAT_ENTREGADO', PAT_REVISADO = 'PAT_REVISADO',
  INVITACION_RECIBIDA = 'INVITACION_RECIBIDA', INVITACION_ACEPTADA = 'INVITACION_ACEPTADA',
  INVITACION_RECHAZADA = 'INVITACION_RECHAZADA', INVITACION_CANCELADA = 'INVITACION_CANCELADA',
  INVITACION_EXPIRADA = 'INVITACION_EXPIRADA', POSTULACION_REGISTRADA = 'POSTULACION_REGISTRADA',
  POSTULACION_CANCELADA = 'POSTULACION_CANCELADA', POSTULACION_RECHAZADA = 'POSTULACION_RECHAZADA',
  TEMA_ASIGNADO = 'TEMA_ASIGNADO', TEMA_ANULADO = 'TEMA_ANULADO',
  TUTOR_ASIGNADO = 'TUTOR_ASIGNADO', TUTOR_REEMPLAZADO = 'TUTOR_REEMPLAZADO',
  INGRESO_RESUELTO = 'INGRESO_RESUELTO',
}
